201460
Akash Kumar Singh
CS 38

1.  Write a NumPy program to reverse an array (first element becomes last).

In [68]:
from numpy import *

a=array([1,2,3,4,5])
c=flipud(a)
print("The reversed array by using In-Built function is ",c)

#Second method
b=a[::-1]
print("The reversed array without using in-built function is ",b)

The reversed array by using In-Built function is  [5 4 3 2 1]
The reversed array without using in-built function is  [5 4 3 2 1]


2.   Write a NumPy program to create a 2-dimensional array of size 2 x 3 also print the shape, type and data type of the array.

In [9]:
from numpy import *

a=array([[1,2,3],[4,5,6]])
print("The array entered is ",a)
print("The shape of the array is ",a.shape)
print("The size of the array is ",a.size)
print("The type of the array is ",type(a))
print("The data type of the array is ",a.dtype)

The array entered is  [[1 2 3]
 [4 5 6]]
The shape of the array is  (2, 3)
The size of the array is  6
The type of the array is  <class 'numpy.ndarray'>
The data type of the array is  int64


3.   Write a NumPy program to create a 2-D array with ones on the diagonal and zeros elsewhere.

In [28]:
from numpy import *

a=eye(4,dtype=int)
print("By using In-Built Function:")
print(a)

# Without using In-Built Function
print()
print()
print("Without using In-Built Function:")
b=zeros([4,4],int)
for i in range(len(b)):
  for j in range(len(b[0])):
    if i==j:
      b[i][j]=ones(1,int)
print(b)

By using In-Built Function:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


Without using In-Built Function:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


4.   Write a NumPy program to multiply and add two 3 x 3 matrices.


In [74]:
from numpy import *

a=array([[1,2,3],[4,5,6],[7,8,9]])
b=array([[3,2,1],[6,5,4],[9,8,7]])
c=zeros([3,3],int)
f=zeros([3,3],int)

d=dot(a,b)
e=a+b
print("The multiplication result by first method is ",d)
print("The addition result by first method is ",e)

#Second Method
for i in range(len(a)):
  for j in range(len(b[0])):
    for k in range(len(b)):
      c[i][j]+=a[i][k]*b[k][j]
      f[i][j]=a[i][j]+b[i][j]

print("The multiplication result by second method is ",c)
print("The addition result by second method is ",f)

The multiplication result by first method is  [[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]
The addition result by first method is  [[ 4  4  4]
 [10 10 10]
 [16 16 16]]
The multiplication result by second method is  [[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]
The addition result by second method is  [[ 4  4  4]
 [10 10 10]
 [16 16 16]]


5.   Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degrees.

In [66]:
from numpy import *

angle=array([0,30,45])

print("Array of Sine of the angles: ",sin(angle*pi/180))
print("Array of Cosine of the angles: ",cos(angle*pi/180))
print("Array of Tangent of the angles: ",tan(angle*pi/180))

Array of Sine of the angles:  [0.         0.5        0.70710678]
Array of Cosine of the angles:  [1.         0.8660254  0.70710678]
Array of Tangent of the angles:  [0.         0.57735027 1.        ]


6.   Write a NumPy program to compute ex, element-wise of a given array.

In [62]:
from numpy import *

x=array([1,2,3,4,5])

result=exp(x)
print(result)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
