201460
Akash Kumar Singh
CS 38

In [15]:
from numpy import *
a=array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("The matrix is:")
print(a)
print()
print()
print("The required output is:")
for i in range(len(a)):
  for j in range(len(a[0])):
    if (i==0 or i==len(a)-1):
      print(a[i][j],end=" ")
    elif (abs(i-j)==1 and j!=0 and j!=len(a)-1):
      print(a[i][j],end=" ")

The matrix is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


The required output is:
1 2 3 4 7 10 13 14 15 16 